[theme]
base = "light"
primaryColor = "#171d3a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#0071a1"
#secondaryBackgroundColor = "#ffffff"
textColor = "#171d3a"
font = "sans serif"

[client]
toolbarMode = "minimal"

